FROM mysql:9.5.0

ENV MYSQL_ROOT_PASSWORD="rootpassword"
ENV MYSQL_DATABASE="pengin_party"
ENV MYSQL_USER="user"
ENV MYSQL_PASSWORD="hogehoge"

# MySQL設定ファイルをコピー
COPY docker/mysql/my.cnf /etc/mysql/conf.d/