// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"pengin_party/internal/application/usecases/user/usecase"
	"pengin_party/internal/infrastructure/redis"
	"pengin_party/internal/infrastructure/repository"
	"pengin_party/internal/presentation/controllers"
)

// Injectors from wire.go:

func InitializeControllers() (*ControllerSet, error) {
	dbInterface, err := repository.Init()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(dbInterface)
	createUserUseCase := usecase.NewCreateUserUseCase(dbInterface, userRepository)
	isExistUserUseCase := usecase.NewIsExistUserUseCase(dbInterface, userRepository)
	userController := controllers.NewUserController(createUserUseCase, isExistUserUseCase)
	serverController := controllers.NewServerController(userController)
	diControllerSet := &ControllerSet{
		ServerController: serverController,
		DB:               dbInterface,
	}
	return diControllerSet, nil
}

// wire.go:

var infrastructureSet = wire.NewSet(repository.Init, redis.NewRedisClient)

var repositorySet = wire.NewSet(repository.NewUserRepository)

var useCaseSet = wire.NewSet(usecase.NewCreateUserUseCase, usecase.NewIsExistUserUseCase)

var controllerSet = wire.NewSet(controllers.NewUserController)

var serverControllerSet = wire.NewSet(controllers.NewServerController)

type ControllerSet struct {
	ServerController *controllers.ServerController
	DB               repository.DBInterface
}
