// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"pengin_party/internal/application/usecases/user/usecase"
	"pengin_party/internal/presentation/controllers"
)

// Injectors from wire.go:

func InitializeControllers() (*ControllerSet, error) {
	createUserUseCase := usecase.NewCreateUserUseCase()
	userController := controllers.NewUserController(createUserUseCase)
	serverController := controllers.NewServerController(userController)
	controllerSet := &ControllerSet{
		ServerController: serverController,
	}
	return controllerSet, nil
}

// wire.go:

var useCaseSet = wire.NewSet(usecase.NewCreateUserUseCase)

var serverControllerSet = wire.NewSet(controllers.NewUserController, controllers.NewServerController)

type ControllerSet struct {
	ServerController *controllers.ServerController
}
